data_raw_basic_path: data/raw/basic/
data_raw_amenities_path: data/raw/amenities/
data_raw_poi_path: data/raw/poi/
data_raw_descriptions_path: data/raw/descriptions/
data_external_neighbor_path: data/external/neighbor_regions_pc.csv
data_external_region_pop_path: data/external/ibge_populacao_bairro.csv
