###################################################
# EXEMPLOS DE CONFIGURAÇÕES
#
# Atenção: as etapas de preprocessamento irão ocorrer
# na ordem que forem especificadas nesse arquivo.
#
# >>> Exemplo:
# - name: nome_da_feature
#   type: float
#   imputation_strategy: constant:0 #(mean, median, constant:<value>)
#   limits: [0.0, 1705.0]
#   transformation: identity # (log, log10, log1p, exp, square, sqrt, identity)
#   discretizer: kmeans:3 # (uniform, quantile)
#   scaler: robust #, (min_max, standard, robust)
#   weight: 1

- name: n_parking_spaces
  type: int
  imputation_strategy: constant:0
  limits: [0, 7]
  discretizer: uniform:6
  scaler: min_max

- name: n_bathrooms
  type: int
  imputation_strategy: constant:0
  limits: [0, 7]
  discretizer: uniform:6
  scaler: min_max

- name: n_bedrooms
  type: int
  imputation_strategy: constant:0
  limits: [0, 8]
  discretizer: uniform:7
  scaler: min_max

- name: area
  type: float
