###################################################
# EXEMPLOS DE CONFIGURAÇÕES
#
# Atenção: as etapas de preprocessamento irão ocorrer
# na ordem que forem especificadas nesse arquivo.
#
# >>> Exemplo:
# - name: nome_da_feature
#   type: float
#   imputation_strategy: constant:0 #(mean, median, constant:<value>)
#   limits: [0.0, 1705.0]
#   transformation: identity # (log, log10, log1p, exp, square, sqrt, identity)
#   discretizer: kmeans:3 # (uniform, quantile)
#   scaler: robust #, (min_max, standard, robust)
#   weight: 1

- name: n_parking_spaces
  type: float
  imputation_strategy: constant:0
  limits: [0, 7]
  discretizer: uniform:6
  scaler: min_max

- name: n_bathrooms
  type: float
  imputation_strategy: constant:0
  limits: [0, 7]
  discretizer: uniform:6
  scaler: min_max

- name: n_bedrooms
  type: float
  imputation_strategy: constant:0
  limits: [0, 8]
  discretizer: uniform:7
  scaler: min_max

- name: area
  type: float
  transformation: log10
  imputation_strategy: constant:1.90
  limits: [1.3, 4]
  discretizer: kmeans:10

- name: n_suites
  type: float
  limits: [0, 4]
  imputation_strategy: constant:0

- name: latitude
  type: float
  imputation_strategy: constant:-21.797
  limits: [-21.9, -21.7]

- name: longitude
  type: float
  imputation_strategy: constant:-46.57
  limits: [-46.7, -46.4]

- name: type_APARTMENT
  type: float

- name: type_HOME
  type: float

- name: type_ALLOTMENT_LAND
  type: float

- name: type_COUNTRY
  type: float

- name: neighborhood
  type: string
  imputation_strategy: constant:outros

- name: time_delta
  type: float

- name: year
  type: float

- name: month
  type: float

- name: day
  type: float

- name: dist_manh
  type: float
  imputation_strategy: mean

- name: dist_square
  type: float
  imputation_strategy: mean

- name: dist
  type: float
  imputation_strategy: mean
