"Distrito Industrial \t": "Distrito Industrial"
"Bortolan Norte I": "Bortolan Norte"
"Loteamento Jardim Nova Europa": "Jardim Europa"
"Jardim das Hortências": "Jardim Das Hortênsias"
"Loteamento Vila Flora II": "Vila Flora"
"Loteamento Residencial Santa Clara II": "Residencial Santa Clara"
"Loteamento Campo das Aroeiras": "Campo das Aroeiras"
"Loteamento Residencial Tiradentes": "Residencial Tiradentes"
"Jardim Filipinas": "Jardim Filipino"
"Jardim Estados": "Jardim dos Estados"
"Chácara Poços De Caldas": "Chacaras Pocos de Caldas"
"Vale das Antas": "Campo das Antas"
"Cascatinha": "Jardim Cascatinha"
"Area Rural de Pocos de Caldas": "Zona Rural"
"Dos Funcionários": "Funcionarios"
