"Distrito Industrial \t": "Distrito Industrial"
"Bortolan Norte I": "Bortolan Norte"
"Loteamento Jardim Nova Europa": "Jardim Europa"
"Jardim das Hortências": "Jardim Das Hortênsias"
"Loteamento Vila Flora II": "Vila Flora"
"Loteamento Residencial Santa Clara II": "Residencial Santa Clara"
"Loteamento Campo das Aroeiras": "Campo das Aroeiras"
"Loteamento Residencial Tiradentes": "Residencial Tiradentes"
"Jardim Filipinas": "Jardim Filipino"
"Jardim Estados": "Jardim dos Estados"
"Chácara Poços De Caldas": "Chacaras Pocos de Caldas"
"Campo das Antas": "Vale das Antas"
"Cascatinha": "Jardim Cascatinha"
"Area Rural de Pocos de Caldas": "Zona Rural"
"Dos Funcionários": "Funcionarios"
"Monte Verde II": "Monte Verde"
"Vila Brasil de Nossa Senhora Aparecida": "Marco Divisório"
"Parque São Sebastião": "Jardim São Sebastião"
"Colinas": "Residencial Vila Colinas"
"Condomínio Morada das Flores": "Morada das Flores"
"Residencial e Industrial Campo Alegre": "Condominio Campo Alegre"
"Real Parque": "Royal Park"
"Chacaras Alto da Boa Vista": "Alto da Boa Vista"
"Sao Conrado": "São Conrado"
"Cristiano Ozorio": "Cristiano Ozório"
"Jardins de Florenca": "Jardins de Florença"
"Chacara Santa Barbara": "Chácara Santa Bárbara"
"Chacara dos Pessegueiros": "Zona Rural"
"Chacara Sao Pedro": "Zona Rural"
