TARGET_COLUMN: "price"

TARGET_SCALE: "identity" # 'log', 'log10', 'log1p', 'log101p

TYPE_MAPPING:
  # -- home -----
  TWO_STORY_HOUSE: "HOME"
  CONDOMINIUM: "HOME"
  # -- apartment -----
  FLAT: "APARTMENT"
  KITNET: "APARTMENT"
  PENTHOUSE: "APARTMENT"
  # -- allotment land -----
  RESIDENTIAL_ALLOTMENT_LAND: "ALLOTMENT_LAND"
  COMMERCIAL_ALLOTMENT_LAND: "ALLOTMENT_LAND"
  # -- business -----
  SHED_DEPOSIT_WAREHOUSE: "BUSINESS"
  BUSINESS: "BUSINESS"
  COMMERCIAL_PROPERTY: "BUSINESS"
  COMMERCIAL_BUILDING: "BUSINESS"
  OFFICE: "BUSINESS"
  HOTEL: "BUSINESS"
  # -- country -----
  "COUNTRY_HOUSE": "COUNTRY"
  "FARM": "COUNTRY"

LONG_INTERVAL: [-46.7, -46.4]

LAT_INTERVAL: [-21.9, -21.76]
